### ISSUE TITLE
Instead of "ignoring cursor pos changes < something"

### ISSUE THREAD

**Issue by basarat** [fcharron/last-cursor-position#12]
It should *replace* the last history.

**Comment by basarat** [comment]
a suggestion only :heart:

**Comment by fcharron** [comment]
If I do that, you will lose the original location where you started to move (less than 3 lines at a time). Assuming you are moving up or down one line at a time, this means that the first last-position you travel to will the line just above or just below the current one, and then a big jump to wherever you were before moving 1 line at a time. Won't that be weird?

**Comment by basarat** [comment]
Having used this palace a lot since then it seems to work perfectly as it is. Thanks 🌹
