### ISSUE TITLE
Last edit curosor location

### ISSUE THREAD

**Issue by Ciantic** [fcharron/last-cursor-position#15]
This is a feature request to implement jumping to last edit location.

I've used Eclipse before, and gotten used to jump back to "last edit" cursor location, it's usually easier to mentally know than last cursor position which accumulates weird positions when just navigating other files.

There is also [a thread, and some interest](https://discuss.atom.io/t/jump-to-last-edit-location-does-atom-support-this/10289) to have this feature among Atom users.

**Comment by fcharron** [comment]
A new package does this:  https://atom.io/packages/goto-last-edit.
