### ISSUE TITLE
Unable to overwrite key bindings

### ISSUE THREAD

**Issue by silver-mx** [fcharron/last-cursor-position#22]
I am trying to use another key binding (ctrl-alt-left), which is not used by linux mint or atom right now. But it seems like the plugin is still  listening to alt-- for some strange reason. May it be hardcoded somewhere so it ignores if it gets overwritten?

**Comment by fcharron** [comment]
Did you try that: https://atom.io/docs/v1.0.19/behind-atom-keymaps-in-depth#removing-bindings ?

**Comment by Benjamin-Dobell** [comment]
Setting the keybinding (and unsetting) works just fine, at least with the latest Atom. For example, if you want to mimic IDEA's keybinding you'd add this to your `keymap.cson`:

```
'atom-workspace':
  'cmd-[': 'last-cursor-position:previous'
  'cmd-]': 'last-cursor-position:next'
  'alt--': 'unset!'
  'alt-_': 'unset!'

'atom-workspace atom-text-editor:not([mini])':
  'cmd-[': 'unset!'
  'cmd-]': 'unset!'
```

I suspect this issue can be safely closed.
