### ISSUE TITLE
Is this still in use?

### ISSUE THREAD

**Issue by wylie39** [fcharron/last-cursor-position#37]
Do you know or is there a way to find out if this is actively being used? If so I would love to step in as the maintainer.

**Comment by fcharron** [comment]
Thanks for your interest! It's hard to know how many people are actively using the extension, but the current stats 
![4F3BD307-FCAD-4916-984D-EB6A1A8C998E](https://user-images.githubusercontent.com/929690/106703393-24c1ca80-65b8-11eb-912b-a4eea08d8aa4.jpeg) indicate it's been relatively popular.

I see no problem in adding you as a maintainer, if it's something you'd like to try.

**Comment by wylie39** [comment]
I would love to try to revive this and clear out the issues log.

**Comment by wylie39** [comment]
Going to close as I have been added.
